---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---


```{r,include=FALSE}
library(ggridges) 
library(patchwork) 
library(dplyr)
library(knitr)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(flexdashboard)
```

```{r,include=FALSE}
data("instacart")
instacart_pro =
  instacart %>%
  janitor::clean_names() %>%
  filter(
    department == "produce"
  )

```


Column {data-width=550}
-----------------------------------------------------------------------

### Chart A
```{r}
as_plot=
  instacart_pro %>%
  group_by(aisle) %>%
  summarize(
    obs=n()) %>%
  mutate(aisle=fct_reorder(aisle,obs)) %>%
   plot_ly(x = ~aisle, y = ~obs, color = ~aisle, type = "bar") %>%
  layout(title = 'Distribution of the aisle in the produce department',
         xaxis = list(title = 'Aisle', zeroline = FALSE),
         yaxis = list(title = 'count', zeroline = FALSE))

 as_plot
  
```

Column {data-width=450}
-----------------------------------------------------------------------
### Chart B
```{r}
  box_plot=
  instacart %>%
  filter(department=="dairy eggs") %>%
  mutate(aisle=fct_reorder(aisle,days_since_prior_order)) %>%
  plot_ly(y=~days_since_prior_order,color=~aisle,type="box",colors="viridis") %>%
  layout(title = 'Distribution of the days since prior order for the ailes
         in the dairy eggs department',
         xaxis = list(title = 'Aisle', zeroline = FALSE),
         yaxis = list(title = 'Days since prior order', zeroline = FALSE))
box_plot
  
```

### Chart C
```{r}
scat_plot=
  instacart %>%
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  mutate(text_label = str_c("obs:", n)) %>%
  plot_ly(x = ~aisle, y = ~n,type="scatter",text = ~text_label) %>%
  layout(title = 'Numbers of items orered in each order',
         xaxis = list(title = 'Aisle', zeroline = FALSE),
         yaxis = list(title = 'count', zeroline = FALSE))
scat_plot
   
  
```
                